name: drift_postgres
description: Postgres implementation and APIs for the drift database package.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  drift: ^2.0.0
  postgres: ^2.6.3
  meta: ^1.8.0
  uuid: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.18.0
  drift_dev:
  drift_testcases:
    path: ../integration_tests/drift_testcases
  build_runner: ^2.4.6

dependency_overrides:
  drift:
    path: ../../drift
