name: drift_crdt
description: A Flutter-only implementation of a drift database, based on the `sqlite_crdt` package.
version: 0.0.1
repository: https://github.com/simolus3/drift
homepage: https://drift.simonbinder.eu/
issue_tracker: https://github.com/simolus3/drift/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  drift: ^2.0.0
  sqflite: ^2.1.0
  path: ^1.8.0
  flutter:
    sdk: flutter
  sqlite_crdt: ^1.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  drift_testcases:
    path: ../extras/integration_tests/drift_testcases
  sqflite_common_ffi: ^2.2.5

flutter:
  assets:
    - test_asset.db

dependency_overrides:
  # Flutter's test packages don't support the latest analyzer yet.
  test_api: 0.6.1
